on:
    push:
        branches:
            - main
    pull_request:

jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.yarn
                  key: yarn-${{ hashFiles('yarn.lock') }}
                  restore-keys: yarn-

            - name: Setup modules
              run: make setup

            - name: ESLint
              run: ./node_modules/.bin/eslint '**/*.ts' --fix

            - name: Prettier
              run: ./node_modules/.bin/prettier --check .
